volumes:
  mongodb_data:

services:
  fastapi:
    environment:
      CORS_HOST: http://localhost:3000
      MONGO_URL: mongodb://murph:password@mongo/admin
      SIGNING_KEY: f4swFgF4563DFG4348dpGazG45egdfggdFg9fGH5
      WAIT_HOSTS: mongo:27017
      WAIT_BEFORE: 5
      WAIT_TIMEOUT: 60
    build:
      context: api
      dockerfile: Dockerfile.dev
    ports:
      - 8000:8000
    volumes:
      - ./api:/app

  ghi:
    image: node:lts-bullseye
    command: /bin/bash run.sh
    working_dir: /app
    volumes:
      - ./ghi:/app
    ports:
      - "3000:3000"
    environment:
      HOST_OS: ${OS}
      NODE_ENV: development
      HOST: "0.0.0.0"
      PUBLIC_URL: http://localhost:3000
      REACT_APP_API_HOST: ${REACT_APP_API_HOST}

  mongo:
    image: mongo:latest
    volumes:
      - ./setup/mongodb:/docker-entrypoint-initdb.d
      - mongodb_data:/data/db
    environment:
      MONGO_INITDB_ROOT_USERNAME: murph
      MONGO_INITDB_ROOT_PASSWORD: password

  mongo-express:
    build:
      context: setup/mongo-express
      dockerfile: Dockerfile.dev
    ports:
      - 8081:8081
    environment:
      ME_CONFIG_MONGODB_SERVER: mongo
      ME_CONFIG_MONGODB_ADMINUSERNAME: murph
      ME_CONFIG_MONGODB_ADMINPASSWORD: password
      WAIT_HOSTS: mongo:27017
      WAIT_BEFORE: 5
      WAIT_TIMEOUT: 60
